"""
agentic_graph.py – ReAct-loop agentic RAG graph with dynamically resolved models and Gemini judge.
"""
from __future__ import annotations

import os
import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))

from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage, ToolMessage

from agentic_state import AgentState
from agentic_tools import retrieve_research_papers
import config

def get_llm():
    """
    Dynamically resolve which LLM to use based on available API keys in environment.
    Precedence: Groq -> Gemini -> Ollama (local)
    """
    # 1. Check for Groq API key
    groq_key = os.getenv("GROQ_API_KEY")
    if groq_key and not groq_key.startswith("your_"):
        try:
            from langchain_groq import ChatGroq
            return ChatGroq(
                model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
                temperature=0.1,
            )
        except ImportError:
            pass

    # 2. Check for Gemini API key
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key and not gemini_key.startswith("your_"):
        try:
            from langchain_google_genai import ChatGoogleGenerativeAI
            return ChatGoogleGenerativeAI(
                model=os.getenv("GEMINI_MODEL", "gemini-1.5-flash"),
                temperature=0.1,
            )
        except ImportError:
            pass

    # 3. Fallback to Ollama local instance
    from langchain_ollama import ChatOllama
    return ChatOllama(
        model=config.OLLAMA_MODEL,
        base_url=config.OLLAMA_BASE_URL,
        temperature=0.1,
        client_kwargs={"timeout": config.OLLAMA_TIMEOUT},
    )

def get_gemini_llm():
    """Specifically retrieve the Gemini LLM for judging/evaluation purposes."""
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key and not gemini_key.startswith("your_"):
        try:
            from langchain_google_genai import ChatGoogleGenerativeAI
            return ChatGoogleGenerativeAI(
                model=os.getenv("GEMINI_MODEL", "gemini-1.5-flash"),
                temperature=0.1,
            )
        except ImportError:
            pass
    return None

# Get resolved LLM and bind our retrieval tool
llm = get_llm()
tools = [retrieve_research_papers]
llm_with_tools = llm.bind_tools(tools)


def call_model(state: AgentState):
    """Node that invokes the LLM with system guidance prepended."""
    messages = state.messages
    
    # Prepend a guiding system prompt on the very first turn
    if not any(isinstance(m, SystemMessage) for m in messages):
        system_msg = SystemMessage(
            content=(
                "You are an expert AI research assistant specializing in machine learning and systems papers. "
                "Use the `retrieve_research_papers` tool to fetch text context whenever asked about papers. "
                "Synthesize your answer strictly based on the retrieved contexts. "
                "Always cite sources and section titles (e.g. '[paper.pdf | h1 > h2]') if available in the text. "
                "If the tool returns no relevant content, state that you do not have enough information."
            )
        )
        messages = [system_msg] + messages
        
    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}


def judge_node(state: AgentState):
    """
    Critic node using Gemini to evaluate the answer generated by Groq.
    Checks if the answer is grounded in retrieved documents.
    """
    messages = state.messages
    
    # 1. Find the proposed final AIMessage answer
    proposed_answer = ""
    target_msg = None
    for msg in reversed(messages):
        if isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
            target_msg = msg
            proposed_answer = msg.content
            break
            
    if not target_msg or not proposed_answer:
        return {"messages": []}
        
    # 2. Find all retrieved context in ToolMessages
    retrieved_contexts = []
    for msg in messages:
        if isinstance(msg, ToolMessage) and msg.name == "retrieve_research_papers":
            retrieved_contexts.append(msg.content)
            
    if not retrieved_contexts:
        # No context retrieved: cannot verify grounding, mark as no_context
        diagnostics = {
            "grounded": False,
            "confidence": 0.0,
            "query_type": "no_context",
            "judge_reason": "No document chunks were retrieved from the database to evaluate grounding."
        }
        updated_msg = AIMessage(
            id=target_msg.id,
            content=target_msg.content,
            additional_kwargs={"diagnostics": diagnostics}
        )
        return {"messages": [updated_msg]}
        
    # 3. Invoke Gemini to grade if keys exist and model class is not Gemini itself (no need to self-judge)
    gemini = get_gemini_llm()
    # Check if Groq was actually resolved (meaning resolved class name contains Groq or Ollama)
    is_groq_or_ollama = "ChatGroq" in str(type(llm)) or "ChatOllama" in str(type(llm))
    
    if not gemini or not is_groq_or_ollama:
        # Default pass-through values if Gemini judge is unavailable
        diagnostics = {
            "grounded": True,
            "confidence": 0.95,
            "query_type": "vector",
            "judge_reason": "Direct pass-through. Gemini critic evaluator bypassed."
        }
        updated_msg = AIMessage(
            id=target_msg.id,
            content=target_msg.content,
            additional_kwargs={"diagnostics": diagnostics}
        )
        return {"messages": [updated_msg]}
        
    context_str = "\n\n---\n\n".join(retrieved_contexts)
    prompt = (
        "You are an expert evaluator. Evaluate if the proposed answer is factually grounded in the provided retrieved context. "
        "Do not allow any claims that cannot be directly supported by the context.\n\n"
        f"Retrieved Context:\n{context_str}\n\n"
        f"Proposed Answer:\n{proposed_answer}\n\n"
        "Instructions:\n"
        "1. Respond ONLY with a JSON object in this format:\n"
        '{"grounded": true/false, "confidence": 0.0 to 1.0, "reason": "concise explanation"}\n'
        "2. Do not write any markdown wrappers or comments outside the JSON."
    )
    
    try:
        response = gemini.invoke([HumanMessage(content=prompt)])
        cleaned_content = response.content.strip().replace("```json", "").replace("```", "").strip()
        res_json = json.loads(cleaned_content)
        
        diagnostics = {
            "grounded": res_json.get("grounded", True),
            "confidence": res_json.get("confidence", 0.95),
            "query_type": "vector",
            "judge_reason": res_json.get("reason", "Evaluation complete.")
        }
    except Exception as exc:
        diagnostics = {
            "grounded": True,
            "confidence": 0.85,
            "query_type": "vector",
            "judge_reason": f"Gemini critic error: {exc}"
        }
        
    updated_msg = AIMessage(
        id=target_msg.id,
        content=target_msg.content,
        additional_kwargs={"diagnostics": diagnostics}
    )
    return {"messages": [updated_msg]}


def route_after_agent(state: AgentState):
    """If tool calls exist, continue to tools node. Otherwise, pass to Gemini judge."""
    messages = state.messages
    last_msg = messages[-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "tools"
    return "judge"


def build_agent_graph(checkpointer=None) -> StateGraph:
    """Build and compile the ReAct agent state graph with critic judge."""
    workflow = StateGraph(AgentState)
    
    # Nodes
    workflow.add_node("agent", call_model)
    workflow.add_node("tools", ToolNode(tools))
    workflow.add_node("judge", judge_node)
    
    # Edges
    workflow.add_edge(START, "agent")
    
    # Conditional edge: after model call, check if tools need to run or evaluate answer
    workflow.add_conditional_edges(
        "agent",
        route_after_agent,
        {
            "tools": "tools",
            "judge": "judge"
        }
    )
    
    # After executing tools, loop back to the agent for synthesis
    workflow.add_edge("tools", "agent")
    
    # After grading the answer, terminate execution
    workflow.add_edge("judge", END)
    
    return workflow.compile(checkpointer=checkpointer)
